### ISSUE TITLE
Downloading Excel (i.e. Athlete Cards) from reverse proxied address

### ISSUE THREAD

**Issue by JDFS404** [jflamy/owlcms4#504]
I tried downloading Athlete Cards via the address via which I have reverse proxied OWLCMS at the venue where the event is being held this Sunday. By downloading the cards I got this message:
![image](https://user-images.githubusercontent.com/26678110/175659257-9b23d825-4741-437c-b4b9-904f03ce8ab7.png)

Log file in Docker didn't show anything strange. I fixed it for now by logging into my VPN and thus going to 192.x.x.x and download them directly.

**Comment by jflamy** [comment]
Works fine behind nginx on kubernetes and behind the Heroku reverse proxy.  I’m afraid you’ll have to figure this one out on your setup.

**Comment by JDFS404** [comment]
> Works fine behind nginx on kubernetes and behind the Heroku reverse proxy.  I’m afraid you’ll have to figure this one out on your setup. 

Maybe something in the proxy header settings. Can you share with me your NGINX config?

**Comment by jflamy-dev** [comment]
nginx is entirely by default.  The secret is the certificate.
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: owlcms
  name: owlcms-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: 'false'
spec:
  tls:
    - hosts:
        - ${OFFICIALS}
      secretName: owlcms-ingress
  rules:
    - host: ${OFFICIALS}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: owlcms-8080
                port:
                  number: 8080
```
